name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: linux-gnu
            os: ubuntu
            target: x86_64-unknown-linux-gnu
          - name: linux-musl
            os: ubuntu
            target: x86_64-unknown-linux-musl
          - name: macos
            os: macos
            target: x86_64-apple-darwin
    name: build [${{ matrix.platform.name }}]
    runs-on: ${{ matrix.platform.os }}-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true
      - name: Set up musl-gcc
        if: matrix.platform.name == 'linux-musl'
        run: |
          sudo apt-get install musl-tools -y
          echo "::set-env name=CC::musl-gcc -static"
          echo "::set-env name=MAKEFLAGS::CC=musl-gcc\\ -static"
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.platform.name }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --target ${{ matrix.platform.target }} --locked --path . --root pandoc-katex
      - name: Package
        id: pkg
        run: |
          tar -C ./pandoc-katex -czf "pandoc-katex-$(git describe --tags --always)-${{ matrix.platform.target }}.tar.gz" .
          echo "::set-output name=file::$(echo pandoc-katex-*.tar.gz)"
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ steps.pkg.outputs.file }}

  deploy-crate:
    if: startsWith(github.ref, 'refs/tags/')
    name: "deploy crate"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}
      - name: Run cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish

  deploy-artifacts:
    if: startsWith(github.ref, 'refs/tags/')
    name: "deploy artifacts"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact [linux-gnu]
        uses: actions/download-artifact@v1
        with:
          name: linux-gnu
          path: .
      - name: Download artifact [macos]
        uses: actions/download-artifact@v1
        with:
          name: macos
          path: .
      - name: Get artifact names
        id: pkg
        run: |
          echo "::set-output name=linux_gnu_file::$(echo pandoc-katex-*-x86_64-apple-darwin.tar.gz)"
          echo "::set-output name=macos_file::$(echo pandoc-katex-*-x86_64-unknown-linux-gnu.tar.gz)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact [linux-gnu]
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.pkg.outputs.linux_gnu_file }}
          asset_name: ${{ steps.pkg.outputs.linux_gnu_file }}
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact [macos]
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.pkg.outputs.macos_file }}
          asset_name: ${{ steps.pkg.outputs.macos_file }}
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
